# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.

#**************
#*** inputs ***
#**************

# List of files
list_files: "samples/samples.tsv"

#A path to where the raw fastq files are stored
input_dir: "/bulk/sycuro_bulk/daniel/diabetes/UC_UT_collaboration/GF_Mouse_Fecal_Pellet_FASTQ_Files/plate3/fastq"   #With no slash at the end

#The name of the output directory (not a path). Change this for not overwriting the output folder in case of rerunning the pipeline after changing some parameters.
output_dir: "output_plate3"

#path of the main snakemake directory
path: "/bulk/sycuro_bulk/daniel/diabetes/UC_UT_collaboration/FemMicro16S_Daniel/FemMicro16S_3"

# Reads format
forward_read_suffix: "_R1_001"
reverse_read_suffix: "_R2_001"

# Reads compressed/decompressed
compression_suffix: ".fastq.gz"     #".fastq.gz" or ".fastq"



#**************
#***** QC *****
#**************

## Cutadapt
## Removing primers if they were sequenced. 
##***If primers need to be removed set this to True and add the primer sequences***

primer_removal: True  #True or False

primers:
fwd_primer: "ACACTGACGACATGGTTCTACAACTCCTRCGGGAGGCAGCAG"
rev_primer: "CTGCTGCCTCCCGYAGGAGTTGTAGAACCATGTCGTCAGTGT"
fwd_primer_rc: "TACGGTAGCAGAGACTTGGTCTGGACTACHVGGGTWTCTAAT"
rev_primer_rc: "ATTAGAWACCCBDGTAGTCCAGACCAAGTCTCTGCTACCGTA"

## Primer detection parameters
# minimum overlap length for primer removal
min_overlap: 15

# maximum error rate for primer removal
max_e: 0.1

## CutAdapt parameters for quality trimming
qf: 20
qr: 20

## minimum length of reads
min_len: 50



#*********************
#***** QC report *****
#*********************

## Positive control samples to visualize for qc report, write down sample names with | delimiter in between
#Example "Zymostandard_S266_L001|Zymostandard_S258_L001"

Positive_samples: "Postive_control_S89_L001"



#***************
#**** DADA2 ****
#***************

##Parameters 

#Default is FALSE. If TRUE, multithreading is enabled and the number of available threads is automatically determined.
#If an integer is provided, the number of threads to use is set
threads: 20

#Truncation length (Make sure your reads still overlap after truncation in order to merge them later!)
#truncLen:
#  - 260
#  - 220


#Maximum error rate (maximum number of “expected errors” allowed in a read)
maxEE:
  - 2
  - 2

#Truncate reads at the first instance of a quality score less than or equal to truncQ.
truncQ: 2

#Subsampling reads for learning error rates
##check the logs/learnErrorRates..out file to check the quantity of bases, reads, and samples utilized for learning error rates.
subsample: False  #True or False
subsample2LearnErrorRate: 0.25


#Default 1e8. The minimum number of total bases to use for error rate learning.
learn_nbases: 100000000


#If "consensus": The samples in a sequence table are independently checked for bimeras, and a consensus decision on each sequence variant is made.
chimera_method: "consensus"


#Initialize random number generator for reproducibility of taxonomy assignment
seed: 100



#*****************
#**** VSEARCH ****
#*****************

Identity: 0.993      # Minimum percent identity for a hit to be considered a match
Maxaccepts: 30       # Maximum number of hits to consider per query
URE_after_GTDB: True #True or False



#*********************
#*** All databases ***
#*********************

## Taxonomy using RDP classifier
RDP_dbs:
 RDP: "/bulk/IMCshared_bulk/shared/dbs/16s_dbs/rdp_train_set_18.fa.gz"
 Silva: "/bulk/IMCshared_bulk/shared/dbs/16s_dbs/silva_nr99_v138.1_train_set.fa.gz"
 GTDB: "/bulk/IMCshared_bulk/shared/dbs/GTDB_16S_r220/GTDB_bac120_arc53_ssu_r220_fullTaxo.fa.gz"
 URE: "/bulk/IMCshared_bulk/shared/dbs/T1D_db/t1d_genus.fasta"

RDP_species:
 RDP: "/bulk/IMCshared_bulk/shared/dbs/16s_dbs/rdp_species_assignment_18.fa.gz"
 Silva: "/bulk/IMCshared_bulk/shared/dbs/16s_dbs/silva_species_assignment_v138.1.fa.gz"
 GTDB: "/bulk/IMCshared_bulk/shared/dbs/GTDB_16S_r220/GTDB_bac120_arc53_ssu_r220_species.fa.gz"
 URE: "/bulk/IMCshared_bulk/shared/dbs/T1D_db/t1d_species.fasta"



## Taxonomy using vsearch
vsearch_DBs: 
 GTDB: "/bulk/IMCshared_bulk/shared/dbs/GTDB_16S_r220/GTDB_bac120_arc53_ssu_r220_fullTaxo.fa.gz"
 URE: "/bulk/IMCshared_bulk/shared/dbs/T1D_db/t1d_full_taxonomy.fasta"
